Repository GDSC-Daejin/project-saboten, pull requests merged in 2023-04, with the labels that each got.

#152 댓글 창에 네비게이션 바 패딩 적용 & 더보기 페이지에서 상세보기 페이지로 이동 기능 구현
  android/src/main/java/app/saboten/androidApp/ui/screens/main/home/more/MoreScreen.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/post/detail/DetailPostPage.kt
Labels: Bug :bug:

#150 [fix/create_post_side_effect]: 게시글 작성 시 중복 작성되지 않도록 변경 & 작성 후 이전 페이지로 전환
  android/src/main/java/app/saboten/androidApp/ui/screens/main/post/write/WritePostPage.kt
  common-client/src/commonMain/kotlin/commonClient/presentation/post/WritePostScreenViewModel.kt
Labels: Bug :bug:

#148 [feature/fix-post-interaction]: Post update 시 스크롤 처음부터 돌아가는 이슈 수정
  android/src/main/java/app/saboten/androidApp/ui/screens/main/category/CategoryScreen.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/home/HomeScreen.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/home/more/MoreScreen.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/profile/ProfileScreen.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/search/SearchScreen.kt
  common-client/src/commonMain/kotlin/commonClient/presentation/main/CategoryScreenViewModel.kt
  common-client/src/commonMain/kotlin/commonClient/presentation/main/HomeScreenViewModel.kt
  common-client/src/commonMain/kotlin/commonClient/presentation/main/MoreScreenViewModel.kt
  common-client/src/commonMain/kotlin/commonClient/presentation/main/ProfileScreenViewModel.kt
  common-client/src/commonMain/kotlin/commonClient/presentation/main/SearchScreenViewModel.kt
Labels: Bug :bug:

#153 [one-tab-login-fix] 구글 로그인 이슈 관련 로그인 방식 수정
  android/src/main/java/app/saboten/androidApp/ui/dialog/GoogleLoginManager.kt
  android/src/main/java/app/saboten/androidApp/ui/dialog/LoginDialog.kt
Labels: Bug :bug:, Feature :new:

#155 게시글 작성 시 카테고리 선택이 보이지 않는 버그 수정 & 제목, 투표를 전부 입력해야 게시글이 작성되도록 변경
  android/src/main/java/app/saboten/androidApp/ui/screens/main/post/write/WritePostPage.kt
Labels: Bug :bug:

#154 홈 페이지에서 SmallPostCard 아이템들의 좋아요, 댓글 클릭 이벤트 구현
  android/src/main/java/app/saboten/androidApp/ui/screens/main/home/HomeScreen.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/home/more/MoreScreen.kt
Labels: Feature :new:

#160 게시글 작성 페이지 - 부적절한 변수명 수정, 프로그레스 바 위치 변경
  android/src/main/java/app/saboten/androidApp/ui/screens/main/post/write/WritePostPage.kt
Labels: Improvement :hammer:

#161 Android/1.0.6 출시
  android/src/main/java/app/saboten/androidApp/ui/dialog/GoogleLoginManager.kt
  android/src/main/java/app/saboten/androidApp/ui/dialog/LoginDialog.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/MainBottomNavigation.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/category/CategoryScreen.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/home/HomeScreen.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/home/more/MoreScreen.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/post/detail/DetailPostPage.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/post/write/WritePostPage.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/profile/ProfileScreen.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/search/SearchScreen.kt
  buildSrc/src/main/kotlin/Properties.kt
  common-client/src/commonMain/kotlin/commonClient/presentation/main/CategoryScreenViewModel.kt
  common-client/src/commonMain/kotlin/commonClient/presentation/main/HomeScreenViewModel.kt
  common-client/src/commonMain/kotlin/commonClient/presentation/main/MoreScreenViewModel.kt
  common-client/src/commonMain/kotlin/commonClient/presentation/main/ProfileScreenViewModel.kt
  common-client/src/commonMain/kotlin/commonClient/presentation/main/SearchScreenViewModel.kt
  common-client/src/commonMain/kotlin/commonClient/presentation/post/WritePostScreenViewModel.kt
Labels: Release :rocket:

#163 게시글 작성 시 카테고리 다중 선택 기능 구현
  android/src/main/java/app/saboten/androidApp/ui/screens/main/post/LargePostCard.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/post/write/WritePostPage.kt
  common-client/src/commonMain/kotlin/commonClient/presentation/post/WritePostScreenViewModel.kt
Labels: Feature :new:

#164 검색 창에서 textField의 위치가 가운데로 오도록 변경
  android/src/main/java/app/saboten/androidApp/ui/screens/main/search/SearchScreen.kt
Labels: Improvement :hammer:

#166 검색 창에서 textField의 위치가 가운데로 오도록 변경
  android/src/main/java/app/saboten/androidApp/ui/screens/main/search/SearchScreen.kt
Labels: Improvement :hammer:

#167 내 프로필에서 아래로 스크롤하고 위로 올리면 항상 새로고침 되는 이슈 해결
  android/src/main/java/app/saboten/androidApp/ui/screens/main/profile/ProfileScreen.kt
Labels: Bug :bug:

#169 로그인하면 현재 페이지를 새로고침해서 데이터를 불러오도록 변경
  android/src/main/java/app/saboten/androidApp/ui/screens/main/category/CategoryScreen.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/home/HomeScreen.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/home/more/MoreScreen.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/post/SmallPostCard.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/post/detail/DetailPostPage.kt
  android/src/main/java/app/saboten/androidApp/ui/screens/main/profile/ProfileScreen.kt
  common-client/src/commonMain/kotlin/commonClient/data/remote/endpoints/PostApi.kt
  common-client/src/commonMain/kotlin/commonClient/presentation/main/CategoryScreenViewModel.kt
  common-client/src/commonMain/kotlin/commonClient/presentation/main/HomeScreenViewModel.kt
  common-client/src/commonMain/kotlin/commonClient/presentation/main/MoreScreenViewModel.kt
  common-client/src/commonMain/kotlin/commonClient/presentation/main/ProfileScreenViewModel.kt
Labels: Bug :bug:, Feature :new:
